"""Deprecated re-export shim.

.. deprecated::
    The content of this module has been split into themed modules (see
    discussion #1660). Import directly from ``qibocal.protocols.constants``,
    ``qibocal.protocols.physics``, ``qibocal.protocols.fitting``,
    ``qibocal.protocols.processing``, ``qibocal.protocols.reporting`` or
    ``qibocal.protocols.plotting`` instead.
"""

from .constants import (
    COLORBAND,
    COLORBAND_LINE,
    DELAY_FIT_PERCENTAGE,
    DISTANCE_XY,
    DISTANCE_Z,
    EXTREME_CHI,
    GHZ_TO_HZ,
    HZ_TO_GHZ,
    KB,
    LEGEND_FONT_SIZE,
    MARGIN,
    MAX_PIXELS,
    MESH_SIZE,
    S_TO_NS,
    SPACING,
    STRING_TYPE,
    TITLE_SIZE,
    V_TO_UV,
    FeatExtractionError,
    H,
    PowerLevel,
)
from .fitting import (
    Range,
    RangeLike,
    chi2_reduced,
    chi2_reduced_complex,
    fallback_frequency,
    fallback_period,
    guess_frequency,
    guess_period,
    quinn_fernandes_algorithm,
    to_range,
)
from .physics import (
    angle_wrap,
    baseline_als,
    effective_qubit_temperature,
    euclidean_metric,
    lorentzian,
    lorentzian_fit,
    lorentzian_with_linear_background,
    readout_frequency,
)
from .plotting import (
    evaluate_grid,
    get_color_state0,
    get_color_state1,
    plot_results,
)
from .processing import (
    build_clustering_data,
    classify,
    clustering,
    compute_assignment_fidelity,
    compute_qnd,
    cumulative,
    horizontal_diagonal,
    marginalize_qubit_counts,
    merging,
    minmax_scaling,
    norm,
    peaks_finder,
    reshaping_raw_signal,
    zca_whiten,
)
from .reporting import (
    eval_magnitude,
    format_error_single_cell,
    round_report,
    significant_digit,
    table_dict,
    table_html,
)

__all__ = [
    "COLORBAND",
    "COLORBAND_LINE",
    "DELAY_FIT_PERCENTAGE",
    "DISTANCE_XY",
    "DISTANCE_Z",
    "EXTREME_CHI",
    "FeatExtractionError",
    "GHZ_TO_HZ",
    "H",
    "HZ_TO_GHZ",
    "KB",
    "LEGEND_FONT_SIZE",
    "MARGIN",
    "MAX_PIXELS",
    "MESH_SIZE",
    "PowerLevel",
    "SPACING",
    "S_TO_NS",
    "STRING_TYPE",
    "TITLE_SIZE",
    "V_TO_UV",
    "Range",
    "RangeLike",
    "chi2_reduced",
    "chi2_reduced_complex",
    "fallback_frequency",
    "fallback_period",
    "guess_frequency",
    "guess_period",
    "quinn_fernandes_algorithm",
    "to_range",
    "angle_wrap",
    "baseline_als",
    "effective_qubit_temperature",
    "euclidean_metric",
    "lorentzian",
    "lorentzian_fit",
    "lorentzian_with_linear_background",
    "readout_frequency",
    "evaluate_grid",
    "get_color_state0",
    "get_color_state1",
    "plot_results",
    "build_clustering_data",
    "classify",
    "clustering",
    "compute_assignment_fidelity",
    "compute_qnd",
    "cumulative",
    "horizontal_diagonal",
    "marginalize_qubit_counts",
    "merging",
    "minmax_scaling",
    "norm",
    "peaks_finder",
    "reshaping_raw_signal",
    "zca_whiten",
    "eval_magnitude",
    "format_error_single_cell",
    "round_report",
    "significant_digit",
    "table_dict",
    "table_html",
]
